name: CI for Accounting service

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build-accounting-microservie:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

        # 2. Install .NET 8 SDK
      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

        # 3. Restore dependencies

      - name: Restore dependencies
        run: |
          cd src/accounting
          dotnet restore

        # Build project
      - name: Build
        run: |
          cd src/accounting/Accounting.csproj
          dotnet build -c Release -bl:./msbuild.binlog

          # Run tests (optional - remove if no tests)
      - name: Test
        run: |
          cd src/accounting/Accounting.csproj
          dotnet test --no-build --verbosity normal

      - name: Pack
        run: |
          cd src/accounting/Accounting.csproj
          dotnet pack -c Release -o ../../nupkg --include-symbols --include-source
