name: CI for Accounting service

on:
  push:
    branches:
      - main

jobs:
  build-accounting-microservie:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: ${{secrets.NUGET_API_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      - name: Restore dependencies
        run: |
          cd src/accounting
          dotnet restore

      - name: Build, test, and pack
        uses: Elskom/build-dotnet@main
        with:
          RESTORE: false
          TEST: true
          PACK: true
          PUSH: false
          SOURCE_NAME: nuget.org
