## ci for ad microservices

name: cd for ad microservices

on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - main

jobs:
  build-ad-mmicroservice:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle # or maven depending on your build tool
      # 3. Build the project
      - name: build
        run: |
          cd src/ad
          ./gradlew build
      ## for maven, replace with: mvn -B clean package
      # 4. Run tests
      - name: test
        run: |
          cd src/ad
          ./gradlew test
      ## for maven, replace with: mvn -B test
