## ci for ad microservices

name: ad-microservices-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ad-mmicroservice:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven # or gradle depending on your build tool
      # 3. Build the project
      - name: build
        run: |
          cd src/ad
          mvn -B package --file pom.xml
      ## for gradle, replace with:  ./gradlew build
      # 4. Run tests
      - name: test
        run: |
          cd src/ad
           mvn -B test
      ## for gradle, replace with: ./gradlew test
