# Github Actions for product catalog
name: ci for product catalog

on:
  push:
    branches:
      - main

jobs:
  Build-product-catalog:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building product catalog..."

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: unit tests
        run: |
          cd src/product-catalog
          go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          run: golangci-lint run
          working-directory: src/product-catalog
