# Github Actions for product catalog
name: ci for product catalog

on:
  push:
    branches:
      - main

jobs:
  Build-product-catalog:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building product catalog..."

      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog ./cmd/product-catalog

      - name: unit tests
        run: |
          cd src/product-catalog
          go test ./...
