## Rust ci
name: ci for shipping microservice

on:
  push:
    branches:
      - main

jobs:
  build-shipping-microservice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust 1.73.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Build Release
        run: cd src/shipping
          cargo build --release

      - name: Run Tests
        run: cd src/shipping
          cargo test --release
      #   run: cargo test --verbose
